// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaNAqzDr26ugjguNxalw5rDgnZDLst0JY',
    appId: '1:797066671846:web:51b2f0efda762c20412d27',
    messagingSenderId: '797066671846',
    projectId: 'registrationpage-dfc1a',
    authDomain: 'registrationpage-dfc1a.firebaseapp.com',
    storageBucket: 'registrationpage-dfc1a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1VUVCuBBEWR6WoTxALqnyV7jOfVP07qA',
    appId: '1:797066671846:android:ecb21f037ce1b951412d27',
    messagingSenderId: '797066671846',
    projectId: 'registrationpage-dfc1a',
    storageBucket: 'registrationpage-dfc1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZdc8yp_3PHTnq6-ABPIkdo4FnpDzxUtE',
    appId: '1:797066671846:ios:442f1bb3eabe0251412d27',
    messagingSenderId: '797066671846',
    projectId: 'registrationpage-dfc1a',
    storageBucket: 'registrationpage-dfc1a.appspot.com',
    iosBundleId: 'com.example.registrationpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZdc8yp_3PHTnq6-ABPIkdo4FnpDzxUtE',
    appId: '1:797066671846:ios:7b781b0f47853f6d412d27',
    messagingSenderId: '797066671846',
    projectId: 'registrationpage-dfc1a',
    storageBucket: 'registrationpage-dfc1a.appspot.com',
    iosBundleId: 'com.example.registrationpage.RunnerTests',
  );
}
